from __future__ import annotations
from typing import Protocol
from t212.models import (AccountInfo, Cash, Position, Pie, PieDetail, Order,
                         Instrument, Exchange, HistoryOrder, Dividend, Transaction)
from t212.pagination import Page


class ApiError(Exception):
    pass


class AuthError(ApiError):
    pass


class RateLimited(ApiError):
    def __init__(self, retry_after: float):
        super().__init__(f"rate limited, retry in {retry_after:.0f}s")
        self.retry_after = retry_after


class T212Client(Protocol):
    async def account_info(self) -> AccountInfo: ...
    async def cash(self) -> Cash: ...
    async def portfolio(self) -> list[Position]: ...
    async def pies(self) -> list[Pie]: ...
    async def pie(self, pie_id: int) -> PieDetail: ...
    async def orders(self) -> list[Order]: ...
    async def instruments(self) -> list[Instrument]: ...
    async def exchanges(self) -> list[Exchange]: ...
    async def history_orders(self, cursor: str | None = None) -> Page[HistoryOrder]: ...
    async def dividends(self, cursor: str | None = None) -> Page[Dividend]: ...
    async def transactions(self, cursor: str | None = None) -> Page[Transaction]: ...
    async def aclose(self) -> None: ...
